# Generated by Django 5.2.10 on 2026-01-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100, verbose_name='Nama Pasien')),
                ('phone', models.CharField(max_length=20, verbose_name='Nomor WhatsApp')),
                ('date', models.DateTimeField(verbose_name='Tanggal & Jam Booking')),
                ('complaint', models.TextField(help_text='Jelaskan secara singkat keluhan yang dialami', verbose_name='Keluhan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pemesanan Jadwal',
                'verbose_name_plural': 'Daftar Pemesanan',
                'ordering': ['-date'],
            },
        ),
    ]
