# Generated by Django 5.2.10 on 2026-01-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruqyah_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default="Ruqyah Syar'iyyah Tanpa Kesurupan", max_length=100)),
                ('therapist_name', models.CharField(default='Ust. Budi Prastowo', max_length=100)),
                ('address', models.TextField(default='Jl. H. Anan No.124 RT01 RW07...')),
                ('phone', models.CharField(default='0856-9739-7988', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('review_count', models.IntegerField(default=415, help_text='Update angka ini sesuai Google Maps')),
                ('map_embed_url', models.TextField(blank=True, help_text='Link embed Google Maps')),
            ],
            options={
                'verbose_name': 'Pengaturan Bisnis',
                'verbose_name_plural': 'Pengaturan Bisnis',
            },
        ),
    ]
